config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :home, only: :index
  devise_for :users
  resources :users
  resources :appointments do
    get :accept, on: :member
    get :reject, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor, class_name: 'User', optional: true
  belongs_to :patient, class_name: 'User'

  validate :appointment_timing, on: :create
  before_destroy :cancelable

  scope :unaccepted, -> { where(doctor_id: nil) }

  def appointment_timing
    return if appointment_date > 5.hour.since

    errors.add(:appointment_date, 'Appointment must be scheduled at least 5 hours before.')
  end

  def can_cancel?
    DateTime.now < (created_at + 1.hour)
  end

  def cancelable
    return if can_cancel?

    errors.add(:base, 'Appointment can not be canceled after 1 hour of scheduling.')
    throw(:abort)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :patient_appointments, class_name: 'Appointment', foreign_key: 'patient_id'
  has_many :doctors, through: :patient_appointments

  has_many :doctor_appointments, class_name: 'Appointment', foreign_key: 'doctor_id'
  has_many :patients, through: :doctor_appointments

  ROLES = { 'patient' => 'patient', 'doctor' => 'doctor', 'admin' => 'admin' }

  enum role: ROLES
  validates :role, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role])
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[destroy accept reject]

  def index
    @appointments = if current_user.patient?
                      current_user.patient_appointments
                    elsif current_user.doctor?
                      current_user.doctor_appointments
                    end
  end

  def new
    # create a new appointment for patient
    @appointment = current_user.patient_appointments.new
  end

  def create
    @appointment = current_user.patient_appointments.new(appointment_params)
    if @appointment.save
      redirect_to appointments_path, notice: 'Appointment created successfully'
    else
      render :new
    end
  end

  def destroy
    @appointment.destroy
    redirect_to appointments_path, notice: 'Appointment Canceled (destroyed) successfully'
  end

  def accept
    @appointment.update(doctor_id: current_user.id)
    redirect_to appointments_path, notice: 'Appointment accepted successfully'
  end

  def reject
    @appointment.update(doctor_id: nil)
    redirect_to appointments_path, notice: 'Appointment rejected successfully'
  end

  private

  def appointment_params
    params.require(:appointment).permit(:appointment_date, :doctor_id, :patient_id)
  end

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user.patient?
      @doctors = User.doctor
    elsif current_user.doctor?
      @appointments = Appointment.unaccepted
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/_appointment.html.erb
<tr>
  <td><%= appointment.patient.name %></td>
  <td><%= appointment.patient.email %></td>
  <td><%= appointment.doctor&.name %></td>
  <td><%= appointment.doctor&.email %></td>
  <td><%= appointment.appointment_date %></td>
  <td>
    <% if current_user.patient? %>
      <% if appointment.can_cancel? %>
        <%= link_to 'Cancel Appointment', appointment_path(appointment), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    <% elsif current_user.doctor? %>
      <% if appointment.doctor == current_user %>
        <%= link_to 'Reject Appointment', reject_appointment_path(appointment) %>
      <% else %>
        <%= link_to 'Accept Appointment', accept_appointment_path(appointment) %>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/appointments/_form.html.erb
<%= form_for @appointment do |f| %>
  <!-- we can set start_hour and end_hour here as well -->
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@appointment.errors.count, "error") %> prohibited
        this appointment from being saved:
      </h2>
      <ul>
        <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.datetime_select :appointment_date, start_year: DateTime.now.year, ampm: true %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/_table.html.erb
<table>
  <thead>
    <tr>
      <th>Patient Name</th>
      <th>Patient Email</th>
      <th>Doctor Name</th>
      <th>Doctor Email</th>
      <th>Appointment Date & time</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= render @appointments %>
  </tbody>
</table>

app/views/appointments/index.html.erb
<h1>Appointments</h1>
<% if current_user.patient? %>
  <%= link_to 'Schedule an appointment', new_appointment_path %>
<% end %>

<%= render 'table' %>

<%= link_to 'Back', root_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>
<%= render 'form' %>

app/views/home/index.html.erb
<h1>Appointment schedule system</h1>

<% if current_user.patient? %>
  <!-- Doctor's listing for patients -->
  <h2>Doctors</h2>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <% @doctors.each do |doctor| %>
        <tr>
          <td><%= doctor.name %></td>
          <td><%= doctor.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Schedule an appointment', new_appointment_path %>
<% elsif current_user.doctor? %>
  <!-- All appointments for doctors -->
  <%= render 'appointments/table' %>
<% end %>
<br>
<%= link_to 'My Appointments', appointments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Applocum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class='notice'><%= notice %></p>
    <p class='alert'><%= alert %></p>
    <% if user_signed_in? %>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
    <% else %>
      <%= link_to('Login', new_user_session_path) %>
    <% end %>
    <%= yield %>
  </body>
</html>